server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  session:
    storage-type: redis
#  추후 session 용도가 아니라면 아래 redis 부분만 추가.
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/board
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

logging:
##  로그 레벨 : trace < debug < info < error 순서의 로그 레벨을 가짐.
##  즉, info 로 설정 시 trace, debug 로그는 출력되지 않음.
  level:
    root: info
#    root: debug
#  file:
#    name: logs/app.log
