# starting point 는 application.yml 파일.
spring:
  profiles:
    active: dev

# 추후 jar 실행 시
# java -jar <jar 파일명>
# 위 코드로 실행이 기본적.
# 아래와 같이 실행 시 application.yml 에 설정을 덮어쓰기
# java "-Dspring.profiles.active=prod" -jar <jar 파일명>



#
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/board
#    username: root
#    password: 0430aa
#
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show_sql: true
#
#logging:
###  로그 레벨 : trace < debug < info < error 순서의 로그 레벨을 가짐.
###  즉, info 로 설정 시 trace, debug 로그는 출력되지 않음.
#  level:
#    root: info
##    root: debug
#  file:
#    name: logs/app.log
#
#mybatis:
#  mapper-locations: classpath:/mapper/**/*.xml